[versions]
kotlin = "2.4.10"
loom = "1.17-SNAPSHOT"
mod-publish = "2.2.0"
minecraft = "1.8.9"
fabric-loader = "0.19.5"
legacy-yarn = "1.8.9+build.4"
devauth = "1.2.2"
oneconfig = "1.2.22"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
legacy-yarn = { module = "net.legacyfabric:legacy-yarn", version.ref = "legacy-yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
oneconfig = { module = "org.polyfrost.oneconfig:1.8.9-ornithe", version.ref = "oneconfig" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
ploceus = { id = "ploceus", version.ref = "loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
